@CardApi_HostAddress = http://localhost:5241

### wszystkie karty
GET {{CardApi_HostAddress}}/api/cards 
Accept: application/json

### wybrana karta
GET {{CardApi_HostAddress}}/api/cards/User1/Card11/actions
Accept: application/json